export const LEGAL_TOPICS = [
  {
    id: "rti",
    labelHindi: "सूचना का अधिकार",
    labelEnglish: "Right to Information",
    labelHinglish: "RTI Filing",
    icon: "FileText",
    color: "#003580",
    act: "RTI Act, 2005",
  },
  {
    id: "property",
    labelHindi: "संपत्ति कानून",
    labelEnglish: "Property Law",
    labelHinglish: "Property Rights",
    icon: "Home",
    color: "#046A38",
    act: "Transfer of Property Act, 1882",
  },
  {
    id: "consumer",
    labelHindi: "उपभोक्ता संरक्षण",
    labelEnglish: "Consumer Protection",
    labelHinglish: "Consumer Rights",
    icon: "ShoppingBag",
    color: "#FF6200",
    act: "Consumer Protection Act, 2019",
  },
  {
    id: "family",
    labelHindi: "पारिवारिक कानून",
    labelEnglish: "Family Law",
    labelHinglish: "Family Matters",
    icon: "Heart",
    color: "#C8960C",
    act: "Hindu Marriage Act / Special Marriage Act",
  },
  {
    id: "labour",
    labelHindi: "श्रम कानून",
    labelEnglish: "Labour Law",
    labelHinglish: "Worker Rights",
    icon: "Briefcase",
    color: "#003580",
    act: "Industrial Disputes Act, 1947",
  },
  {
    id: "disability",
    labelHindi: "दिव्यांग अधिकार",
    labelEnglish: "Disability Rights",
    labelHinglish: "RPWD Rights",
    icon: "Accessibility",
    color: "#046A38",
    act: "RPWD Act, 2016",
  },
  {
    id: "schemes",
    labelHindi: "सरकारी योजनाएं",
    labelEnglish: "Government Schemes",
    labelHinglish: "PM Schemes",
    icon: "Building",
    color: "#FF6200",
    act: "PM schemes & entitlements",
  },
  {
    id: "fir",
    labelHindi: "प्रथम सूचना रिपोर्ट",
    labelEnglish: "FIR & Police Complaint",
    labelHinglish: "FIR Filing",
    icon: "Shield",
    color: "#4A5568",
    act: "CrPC Section 154",
  },
];